### ISSUE TITLE
Bug in `MeanLength` filter

### ISSUE THREAD

**Issue by sadra-barikbin** [oscar-project/ungoliant#70]
There should be an `abs()` in this line so as to the logic becomes true:
https://github.com/oscar-corpus/ungoliant/blob/6f1571516fd3337fe8fe9e6c533144e73d2d7017/src/filtering/sentence.rs#L109

Tor reproduce, we could add this assertion the `mean_default` test in `filtering/sentence.rs`:

```rust
let short_invalid: String = ['a'].iter().cycle().take(80).collect();
assert_eq!(f.detect(&short_invalid), false);
```
Output:
```
---- filtering::sentence::tests::mean_default stdout ----
init rng   : mu:100.000 sig:10.000
from filter: mu:99.492 sig:9.989
thread 'filtering::sentence::tests::mean_default' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`'
```

**Comment by Uinelj** [comment]
Thanks a lot for the fix!
