### ISSUE TITLE
[BUG] Error when downloading full CC snapshot

### ISSUE THREAD

**Issue by ngan-nt** [oscar-project/ungoliant#94]
**Describe the bug**
If I only sample 0.01% of total files, `ungoliant download` works well.
However, if I download full CC snapshot, the following error appears.

I'm using the latest version of ungoliant.

**To Reproduce**
```
from os import mkdir, path
from subprocess import run
import argparse
import random
import requests

import multiprocessing


tmp_download_dir_name = f"tmp/"

if path.exists(tmp_download_dir_name):
    run(f"rm -r {tmp_download_dir_name}", shell=True)
run(f"mkdir {tmp_download_dir_name}", shell=True)

num_proc = multiprocessing.cpu_count()

run(f"wget https://data.commoncrawl.org/crawl-data/CC-MAIN-2020-40/wet.paths.gz", shell=True)
run(f"gzip -d wet.paths.gz", shell=True)
paths_name = f"wet-CC-MAIN-2020-40.paths"
run(f"mv wet.paths {paths_name}", shell=True)
segments = open(paths_name, "r").readlines()

run(f"ungoliant download -t={num_proc} {paths_name} {tmp_download_dir_name}", shell=True)
```

**Screenshots**
![Screenshot from 2023-02-28 22-56-22](https://user-images.githubusercontent.com/22459815/222017678-483f5b76-2ac1-4f15-9208-38e37454dd38.png)

**Comment by Uinelj** [comment]
Hello @ngan-nt .

Following the logs, it seems that the error comes from the [service being unavailable](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/503). 
How much time did the process run before running into these errors?

**Comment by Uinelj** [comment]
Hey. This is what i'm implying. IIRC we had similar issues and had to re-run a process with the missing shards. We however should provide an easier way of re-trying failed download attempts.
